START = 'start'

'----------------------------------'
JOZVE_SABT = 'jozve_sabt'
JOZVE_SEARCH = 'jozve_search'
JOZVE_DARKHAST = 'jozve_darkhast'
'----------------------------------'
SOURCE_SABT = 'source_sabt'
SOURCE_SEARCH = 'source_search'
SOURCE_DARKHAST = 'source_darkhast'
'----------------------------------'
RECORDED_SABT = 'recorded_sabt'
RECORDED_SEARCH = 'recorded_search'
RECORDED_DARKHAST = 'recorded_darkhast'
'----------------------------------'
