START = 'start'

'----------------------------------'
DOCUMENT_SUBMISSION = 'document_submission'
DOCUMENT_SEARCH = 'document_search'
DOCUMENT_SUBMISSION = 'document_submission'
'----------------------------------'
SOURCE_SUBMISSION = 'source_submission'
SOURCE_SEARCH = 'source_search'
SOURCE_SUBMISSION = 'source_submission'
'----------------------------------'
RECORDED_SUBMISSION = 'recorded_submission'
RECORDED_SEARCH = 'recorded_search'
RECORDED_SUBMISSION = 'recorded_submission'
'----------------------------------'
